branches:
  except:
  - experimental

matrix:
  include:
  - language: node_js
    node_js:
      - 10

    addons:
      apt:
          packages:
            # Ubuntu 16+ does not install this dependency by default, so we need to install it ourselves
            - libgconf-2-4
    cache:
      # Caches $HOME/.npm when npm ci is default script command
      # Caches node_modules in all other cases
      npm: true
      directories:
        # we also need to cache folder with Cypress binary
        - ~/.cache
    install:
      - cd UGWFrontend
    script:
      - bash ./ci-build.sh
  - language: rust
    rust: nightly
    cache: cargo
    services:
    - redis-server
    - docker
    env:
    - SECRET=test
    - MAIL_JET_USER=test
    - MAIL_JET_KEY=test
    - REDIS_PATH="redis://127.0.0.1:6379/"
    - INSTA_CID="test"
    - INSTA_SECRET="test"
    - RUST_BACKTRACE=1
    - DEVELOPMENT="true"
    script:
    - cd UGWBackend
    - bash ./ci-build.sh