# Kubernetes deployment and service file
# run k8s-first-deploy.sh
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ugw-backend
  labels:
    app: ugw-backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ugw-backend
  template:
    metadata:
      labels:
        app: ugw-backend
    spec:
      imagePullSecrets:
      - name: regcred
      containers:
      - name: ugw-backend-pod
        image: dr.fosefx.com/ugw-backend
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: REDIS_PATH
          value: redis://db.ugw.svc.cluster.local:6379
        - name: SECRET
          valueFrom:  
            secretKeyRef:
              name: ugw-secret
              key: secret
        - name: MAIL_JET_USER
          valueFrom:  
            secretKeyRef:
              name: ugw-secret
              key: mju
        - name: MAIL_JET_KEY
          valueFrom:  
            secretKeyRef:
              name: ugw-secret
              key: mjk
        - name: INSTA_CID
          valueFrom:  
            secretKeyRef:
              name: ugw-secret
              key: icid
        - name: INSTA_SECRET
          valueFrom:  
            secretKeyRef:
              name: ugw-secret
              key: is
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ugw-db
  labels:
    app: ugw-db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ugw-db
  template:
    metadata:
      labels:
        app: ugw-db
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
      - name: ugw-db-pod
        image: dr.fosefx.com/ugw-db
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SECRET
          valueFrom:  
            secretKeyRef:
              name: ugw-secret
              key: secret
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ugw-redis
  labels:
    app: ugw-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ugw-redis
  template:
    metadata:
      labels:
        app: ugw-redis
    spec:
      containers:
      - name: ugw-redis-pod
        image: redis:alpine
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: ugw-expose-service
spec:
  type: NodePort
  selector:
    app: ugw-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000
---
apiVersion: v1
kind: Service
metadata:
  name: db
spec:
  type: ClusterIP
  selector:
    app: ugw-db
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080